### ISSUE TITLE
Рекомендации. Server.

### ISSUE THREAD

**Issue by mayerkv** [burning-gg/to-do-list-assignment#1]
https://github.com/burning-gg/to-do-list-assignment/blob/9d6e1b37e1900ee7c109eab7332aea33c8cbbb81/server/routes/Users.js#L24

Могу ошибаться, но вроде после вызова `res.json()` функция продолжит выполнение, если это не предусмотрено логикой, то стоит добавить `return`.

---

https://github.com/burning-gg/to-do-list-assignment/blob/9d6e1b37e1900ee7c109eab7332aea33c8cbbb81/server/routes/Users.js#L28

Выше используется `async/await`, тут переходит на `promise chain`. Такой код хуже читается, лучше использовать один стиль. На мой взгляд лучше читается `async/await`.

---

https://github.com/burning-gg/to-do-list-assignment/blob/9d6e1b37e1900ee7c109eab7332aea33c8cbbb81/server/routes/Users.js#L10

Именование переменных. Часть в camelcase, часть в uderscore. В JS принято camelcase.

---

https://github.com/burning-gg/to-do-list-assignment/blob/9d6e1b37e1900ee7c109eab7332aea33c8cbbb81/server/routes/Users.js#L71

Ключ `secretstring` лучше вынести в конфиги, а те, в свою очередь, брать из переменных окружения. Хранить в исходниках не безопасно.

---

https://github.com/burning-gg/to-do-list-assignment/blob/9d6e1b37e1900ee7c109eab7332aea33c8cbbb81/server/routes/Tasks.js#L12

Тут `await` ничего не делает.

---

https://github.com/burning-gg/to-do-list-assignment/blob/9d6e1b37e1900ee7c109eab7332aea33c8cbbb81/server/routes/Tasks.js#L7

Было бы не плохо добавить постраничный вывод. Условно `GET /tasks?page=1&size=10` должен возвращать первые 10 тасков.

Для того чтобы смапить пользователей на таски можно воспользоваться возможностями ORM, описав отношения сущностей: https://sequelize.org/master/manual/assocs.html. Такой подход часто приводит к проблемам производительности, но в небольших проектах можно юзать (если сущностей и связей между ними не много).

Если не используешь ассоциации ORM, то алгоритм должен быть такой:
- получить таски
- вытащить из тасков айдишники пользователей
- по полученным айдишникам получить список пользователей одним запросом (SQL `where in ()`)
- полученный список пользователей преобразовать в мапку типа `map<userId, User>`, чтобы можно было по ключу сразу получать пользователя
- цикл по таскам, в котором по userId получаешь пользователя из мапы, кладешь в таску

---

https://github.com/burning-gg/to-do-list-assignment/blob/9d6e1b37e1900ee7c109eab7332aea33c8cbbb81/server/config/config.json#L2

Значения в конфигах стоит вынести в переменные окружения. Сами конфиги не стоит делать в коде на дев/прод.

---

https://github.com/burning-gg/to-do-list-assignment/blob/9d6e1b37e1900ee7c109eab7332aea33c8cbbb81/server/index.js#L16

Для управления схемой базы данных в продакшн такой метод не подойдет. Для версионирования необходимо использовать миграции: https://sequelize.org/master/manual/migrations.html

**Comment by burning-gg** [comment]
Переделал, добавил, пофиксил большую часть, спасибо.

Но не понял, как связаны миграции с `db.sequelize.sync()` в последнем абзаце, и если `db.sequelize.sync()` не подходит, то каким образом подключается БД?
